#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

home:
    path: /
    controller: App\Controller\HomeController::index

formulaire:
    path: /pages/formulaire
    controller: App\Controller\EtudeController::viewEtude

ajout:
    path: /pages/ajoutFormulaire
    controller: App\Controller\EtudeController::addEtude

    