#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

login:
    path: /
    controller: App\Controller\SecurityController::login

formulaire:
    path: /pages/formulaire
    controller: App\Controller\EtudeController::viewEtude

ajout:
    path: /pages/ajoutFormulaire
    controller: App\Controller\EtudeController::addEtude


    